<?php

$pastas = ["./"]; // pasta para escanear

// assinaturas suspeitas
$assinaturas = [
    "eval(",
        "base64_decode(",
            "shell_exec(",
                "system(",
                    "passthru(",
                        "exec(",
                            "gzinflate("
                            ];

                            function escanear($pasta, $assinaturas){
                                $arquivos = scandir($pasta);

                                    foreach($arquivos as $arquivo){

                                            if($arquivo == "." || $arquivo == "..") continue;

                                                    $caminho = $pasta . "/" . $arquivo;

                                                            if(is_dir($caminho)){
                                                                        escanear($caminho, $assinaturas);
                                                                                } else {

                                                                                            $conteudo = file_get_contents($caminho);
                                                                                                        $hash = md5_file($caminho);

                                                                                                                    foreach($assinaturas as $virus){
                                                                                                                                    if(strpos($conteudo, $virus) !== false){
                                                                                                                                                        echo "⚠️ POSSÍVEL VÍRUS: $caminho\n";
                                                                                                                                                                            echo "Assinatura: $virus\n";
                                                                                                                                                                                                echo "Hash: $hash\n\n";
                                                                                                                                                                                                                }
                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                        foreach($pastas as $p){
                                                                                                                                                                                                                                            escanear($p, $assinaturas);
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                            ?><?php

                                                                                                                                                                                                                                            class SecurityScanner {
                                                                                                                                                                                                                                                private $scanPath;
                                                                                                                                                                                                                                                    private $maliciousExtensions = ['php', 'exe', 'js', 'bat', 'cmd', 'sh'];

                                                                                                                                                                                                                                                        public function __construct($scanPath) {
                                                                                                                                                                                                                                                                $this->scanPath = $scanPath;
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                        public function scan() {
                                                                                                                                                                                                                                                                                if (!is_dir($this->scanPath)) {
                                                                                                                                                                                                                                                                                            throw new Exception('Scan path is not a directory.');
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                            $files = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($this->scanPath));
                                                                                                                                                                                                                                                                                                                    $maliciousFiles = [];

                                                                                                                                                                                                                                                                                                                            foreach ($files as $file) {
                                                                                                                                                                                                                                                                                                                                        if ($this->isMalicious($file)) {
                                                                                                                                                                                                                                                                                                                                                        $maliciousFiles[] = $file;
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                    return $maliciousFiles;
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                            private function isMalicious($file) {
                                                                                                                                                                                                                                                                                                                                                                                                    return in_array(pathinfo($file, PATHINFO_EXTENSION), $this->maliciousExtensions);
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                            public function report($maliciousFiles) {
                                                                                                                                                                                                                                                                                                                                                                                                                    if (empty($maliciousFiles)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                echo "No malicious files found.\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo "Malicious files detected:\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    foreach ($maliciousFiles as $file) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                echo "$file\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public static function main() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $scanner = new self('/path/to/scan'); // specify the path to scan
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $maliciousFiles = $scanner->scan();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $scanner->report($maliciousFiles);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (Exception $e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            echo 'Error: ' . $e->getMessage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Execute the scanner
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        SecurityScanner::main();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?>